# ---------------------------------------------------------
# Stage 1 - Build Stage
# ---------------------------------------------------------
FROM maven:3.9.6-eclipse-temurin-21 AS builder

WORKDIR /build

COPY pom.xml .
RUN mvn -B -q -e -C -T 1C dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests
  
  
  # ---------------------------------------------------------
  # Stage 2 - Runtime Stage
  # ---------------------------------------------------------
FROM eclipse-temurin:21-jre
  
  # ---------------------------
  # REQUIRED BY MOSIP CI
  # ---------------------------
ARG SOURCE
ARG COMMIT_HASH
ARG COMMIT_ID
ARG BUILD_TIME

LABEL source=${SOURCE}
LABEL commit_hash=${COMMIT_HASH}
LABEL commit_id=${COMMIT_ID}
LABEL build_time=${BUILD_TIME}
  # ---------------------------

WORKDIR /app

COPY --from=builder /build/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","/app/app.jar"]